name: job1
on:
  workflow_dispatch:
  
jobs:
  testjob:
    uses: .github/workflows/job2.yml@main

  checkJob:
    if: ${{ always() && ! ${{ skipped() || cancelled() }} }}
    needs: testjob
    uses: .github/workflows/job2.yml@main
