name: job1
on:
  workflow_dispatch:
  
jobs:
  testjob:
    uses: abhishekNKamble/github-slideshow/.github/workflows/Job2.yml@main

  checkJob:
    if: always() && !cancelled() && !failure()
    needs: testjob
    uses: abhishekNKamble/github-slideshow/.github/workflows/Job2.yml@main
