name: job2
on:
  workflow_dispatch:
  workflow_call:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: |
          sleep 10s
          echo "Test passed"
          exit 1
